language: cpp
sudo: required
compiler:
    - gcc
    - clang
    # Change this to your needs
before_install:
    - sudo export LIBS= && sudo export CFLAGS= && cd tools/script/linux/install/ && sudo bash install_environment.sh --full && cd ../../../../
script: cd pf/core/proj.linux && cmake ./ && make
