language: cpp
sudo: required
compiler:
    - gcc
    - clang
    # Change this to your needs
before_install:
    - cd tools/script/linux/install/ && sudo sh install_environment.sh --full
script: cd pf/core/proj.linux && cmake ./ && make
